version: '3.9'
services:
  jupyter:
    container_name: "jupter"
    hostname: "jupter"
    build:
      context: ./streaming
      dockerfile: Dockerfile
    ports:
    - "8888:8888"
    
    volumes:
      - .:/code